<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>

<div class='span-22 last'>
	<div class='span-16' style='font-size: 1.5em;'>
		<a href='<?php echo $this->baseUrl(); ?>/admin/account' class='hypertext'>Accounts</a> &raquo;
		<a href='<?php echo $this->baseUrl(); ?>/account/modify/edit?id=<?php echo $this->id; ?>' class='hypertext'><?php echo $this->account->getUsername(); ?></a> &raquo;
		Mappings
	</div>
	<div class='span-6 last'>
		<a href='<?php echo $this->baseUrl(); ?>/account/mappings/edit?accountId=<?php echo $this->account->getId(); ?>' class='hypertext create-mapping'>Create a new mapping</a>
	</div>
</div>
<hr class='space'/>
<div>
	<form id='search'>
		<input type='hidden' name='page' value='1'>
		<input type='hidden' name='old-page' value='1'>
		<input type='hidden' name='accountId' value='<?php echo $this->account->getId(); ?>'>
	</form>
</div>
<div class='span-15 colborder'>
	<form id='form-edit'>
		<input type='hidden' name='base-url' value='<?php echo $this->baseUrl(); ?>'>
		<input type='hidden' name='accountId' value='<?php echo $this->account->getId(); ?>'>
	</form>
	<form id='form-submit'>
		<div class='block'>
			<div id='select-actions' class='span-15'>
				Select: <span class='hypertext select-all'>All</span>, <span class='hypertext select-none'>None</span>
			</div>
			<div class='search-results span-15 last'>
				<div style='padding: 10px;' class='span-15'>
					<div class='content'></div>
				</div>
				<div id='with-selected'>
					With selected: <span class='hypertext selected-delete'>Delete</span>
				</div>
			</div>
		</div>
	</form>
</div>
<div class='span-6 last' style='text-align: justify;'>
	<p>
	Account maps assist in mapping usernames that may exist or be
	used in other authentication methods to IDs that are stored
	in savory.
	</p>
	<p>
	Maps are most useful if you have users with several different
	account names and want those users to be able to access their
	saved audits, policies, etc, even if they log in with a different
	authentication method.
	</p>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
