		</div>
		<div id='footer'>
			<div class='append-bottom'>
				<ul>
					<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about'>version <?php echo $this->config->misc->version; ?></a>
					<li><a class='hypertext' target='_blank' href='<?php echo $this->config->links->wiki; ?>'>wiki</a>
					<li><a class='hypertext' href='<?php echo $this->config->links->faq; ?>'>FAQ</a>
				</ul>
			</div>
		</div>
	</body>
</html>
