<h1>Can <?php echo _APPLICATION; ?> scan through my firewall ?</h1>
<p>
	If your firewall blocks all inbound traffic, ScanMeNow will not
	be able to detect vulnerabilities present on your system. The
	good news is that others on the Internet probably will not be
	able to access your computer either.
</p>
<p>
	Because personal firewalls can accidentally be disabled, it is
	recommended to temporarily permit traffic from the ScanMeNow server
	perform the ScanMeNow, then remove the firewall filters you previously added.
</p>
