<h1>What alerts should I be concerned about?</h1>
<p>
	<div>
		<b>Vulnerable</b> type alerts
	</div>
	<div>
		You should address any 'Vulnerable' type alerts.
		These alerts represent the greatest threat to your
		system that can permit an attacker to gain access
		to your system.
	</div>
</p>
<p>
	<div>
		<b>Warning</b> type alerts
	</div>
	<div>
		You should review any 'Warning' type alerts for your
		system. Many of the 'Warning' type alerts simply indicate
		that an attacker may detect the presence of a service
		on your system and, in many cases, may safely be ignored
		<b>unless</b> you do not intend the detected service to
		be widely available to the general Internet.
	</div>
</p>
<p>
	<div>
		<b>Informational</b> type alerts
	</div>
	<div>
		These alerts display additional details about the scan
		that was performed including the host name detected,
		IP route to your host and other information.
	</div>
</p>
