<h1>Why does the scan only complete a portion of the total plugins available?</h1>
<p>
	While ScanMeNow has over 10,000 tests available, it will only scan
	for those vulnerabilities possibly present on your system given the
	open ports, applications or operating system detected.
</p>
<p>
	For example, ScanMeNow might not perform Microsft IIS web server
	checks against a detected Apache installation. It is very unusual
	for every ScanMeNow test to be performed against your system.
</p>
