<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>

<div class='pagehead span-24'>
	<div class='wrapper content'>
<div class='span-22 last'>
	<div id='page-header'>
		<div class='span-4' style='font-size: 1.5em;'>
			Permissions
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
	</div>
</div>
<hr class='space'/>
<div class='span-22 last' style='border-bottom: 1px solid #ccc;'>
	<div class='span-3' style='background-color: #3274D0;'>
		<div style='padding-left: 5px;' class='nohover'>
			<a href='<?php echo $this->baseUrl(); ?>/permissions/capability' class='indexTab'>Capabilities</a>
		</div>
	</div>
</div>

<div class='span-22 last' style='border-color: 1px solid #fff; position: relative;'>
	<form id='form-edit'>
		<input type='hidden' name='base-url' value='<?php echo $this->baseUrl(); ?>'>
	</form>

	<div id='permissions' class='block clearfix menu-content span-22'>
		<div class='prepend-top'>
			<strong>Capability name</strong>
			<br>
			<form id='form-submit'>
				<input type='text' name='permission' class='span-22'>
			</form>
		</div>

		<div class='span-22 last form-ops prepend-top' style='text-align: right;'>
			<input id='btn-save' type='button' value='Save' style='margin-left: 20px;'>
			<a class='hypertext cancel' style='padding-left: 20px;' href='<?php echo $_SERVER["HTTP_REFERER"]; ?>'>cancel</a>
		</div>
	</div>
</div>
	</div>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
