<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>

<div class='pagehead span-24'>
	<div class='wrapper content'>
<div class='span-22 last'>
	<div id='page-header'>
		<div class='span-4' style='font-size: 1.5em;'>
			Permissions
			<img class='progress' src='<?php echo $this->baseUrl(); ?>/usr/images/spinner.gif'>
		</div>
	</div>
</div>
<hr class='space'/>
<div class='span-22 last' style='border-bottom: 1px solid #ccc;'>
	<div class='span-3' style='background-color: #3274D0;'>
		<div style='padding-left: 5px;' class='nohover'>
			<a href='<?php echo $this->baseUrl(); ?>/fresh' class='indexTab'>Capabilities</a>
		</div>
	</div>
</div>

<div class='span-22 last' style='border-color: 1px solid #fff; position: relative;'>
	<form id='form-edit'>
		<input type='hidden' name='base-url' value='<?php echo $this->baseUrl(); ?>'>
		<input type='hidden' name='page' value='1'>
	</form>

	<div class='span-22 prepend-top'>
		<div class='span-20'>
			<div style='color: #999; padding-bottom: 5px;'>
				Capabilities are used to control access to major portions of the system. 
			</div>
		</div>
		<div class='span-2 last' style='text-align: right;'>
			<a class='hypertext' href='<?php echo $this->baseUrl(); ?>/permissions/capability/create'>add new</a>
		</div>
	</div>

	<div id='permissions' class='block clearfix menu-content span-22'>
		<div id='content' class='content' style='padding-top: 10px;'></div>
	</div>

	<div id='pager' class='prepend-top append-bottom span-22' style='text-align: center;'></div>
</div>
</div>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
