<?php if ($this->action == 'index'): ?>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/plugins/jquery.pager.js' type='text/javascript'></script>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/permissions/capability/index.js' type='text/javascript'></script>
<?php elseif ($this->action == 'create'): ?>
<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/permissions/capability/create.js' type='text/javascript'></script>
<?php endif; ?>
