<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>

<div class='pagehead span-24'>
	<div class='wrapper content'>
<div class='span-22 last'>
	<div class='span-12' style='font-size: 1.5em;'>
		Your Account
	</div>
</div>

<hr class='space'/>

<div class='settings-block span-22'>
	<div class='header bigtext'>Account Information</div>
	<div class='span-20 prepend-top append-1 prepend-1 append-bottom'>
		<?php if ($this->session->acl->isAllowed('Capability', array('admin_operator', 'can_change_password'))): ?>
		<div class='span-7'>
			<a class='hypertext' href='<?php echo $this->baseUrl(); ?>/settings/password'>Change password</a>
		</div>
		<?php endif; ?>
		<div class='span-7'>
			<a class='hypertext' href='<?php echo $this->baseUrl(); ?>/settings/contact'>Name and contacts</a>
		</div>
	</div>
</div>

<hr class='space'/>

<div class='settings-block span-22'>
	<div class='header bigtext'>Account Preferences</div>
	<div class='span-22 prepend-top append-1 prepend-1 append-bottom'>
		<div class='span-7'>
			<a class='hypertext' href='<?php echo $this->baseUrl(); ?>/settings/interface'>User interface</a>
		</div>
	</div>
</div>
	</div>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
