<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
"http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<title><?php echo _APPLICATION; ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<meta name="copyright" content="&copy;">
		<meta name="Author" content="Tim Rupp">
		<link rel='icon' type='image/png' href='<?php echo $this->baseUrl(); ?>/usr/images/favicon.png'>
		<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl(); ?>/usr/html/styles/styles.css'>
		<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl(); ?>/usr/html/styles/jquery-ui.css'>
		<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl(); ?>/usr/html/styles/jquery-ui.override.css'>
		<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl(); ?>/usr/html/styles/pager.css'>

		<link rel='stylesheet' href='<?php echo $this->baseUrl(); ?>/usr/html/styles/blueprint/screen.css' type='text/css' media='screen, projection'>
		<!--[if lt IE 8]><link rel='stylesheet' href='<?php echo $this->baseUrl(); ?>/usr/html/styles/blueprint/ie.css' type='text/css' media='screen, projection'><![endif]-->
		<link rel='stylesheet' href='<?php echo $this->baseUrl(); ?>/usr/html/styles/blueprint.override.css' type='text/css' media='screen, projection'>

		<?php @include sprintf('%s/%s/views/scripts/%s/styles.phtml', _MODPATH, $this->module, $this->controller); ?>

		<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/jquery.min.js' type='text/javascript'></script>
		<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/jquery/ui/1.8.2/jquery-ui.custom.js' type='text/javascript'></script>

		<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/php.min.js' type='text/javascript'></script>
		<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/firebugx.js' type='text/javascript'></script>
		<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/step.js' type='text/javascript'></script>

		<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/site/init.js' type='text/javascript'></script>

		<?php @include sprintf('%s/%s/views/scripts/%s/javascript.phtml', _MODPATH, $this->module, $this->controller); ?>
		<?php @include sprintf('%s/%s/views/scripts/%s/rss.phtml', _MODPATH, $this->module, $this->controller); ?>

		<script src='<?php echo $this->baseUrl(); ?>/usr/html/javascript/site/ready.js' type='text/javascript'></script>
	</head>
	<body>
		<div id='messageBar'>
			<div class='message error'>
				<span class='content'></span>
				&nbsp;&nbsp;
				<span class='hypertext close'>close</span>
			</div>
			<div class='message ok'>
				<span class='content'></span>
				&nbsp;&nbsp;
				<span class='hypertext close'>close</span>
			</div>
			<div class='message info'>
				<span class='content'></span>
				&nbsp;&nbsp;
				<span class='hypertext close'>close</span>
			</div>
		</div>

		<div class='container clearfix'>
			<div id='header'>
				<div class='prepend-top append-bottom span-12'>
					<span class='large logo'>
						<a href='<?php echo $this->baseUrl(); ?>'><?php echo _APPLICATION; ?></a>
					</span>
				</div>
				<div id='links' class='prepend-top span-12 last' style='text-align: right;'>
					<?php if ($this->session === null): ?>
					&nbsp;
					<?php else: ?>
					<ul>
						<li><a href='<?php echo $this->baseUrl(); ?>/settings/modify/edit'>settings</a>
						<?php if ($this->session->acl->isAllowed('Capability', array('admin_index', 'admin_operator'))): ?>
						<li><a href='<?php echo $this->baseUrl(); ?>/admin'>admin</a>
						<?php endif; ?>
						<li><a href='<?php echo $this->baseUrl(); ?>/account/login/logout'>logout</a>
					</ul>
					<?php endif; ?>
				</div>
			</div>
