<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>

<div class='pagehead span-24'>
	<div class='wrapper content'>
<div class='span-22 last'>
	<div class='span-12' style='font-size: 1.5em;'>
		<a href='<?php echo $this->baseUrl(); ?>/settings/modify/edit?id=<?php echo $this->id; ?>' class='hypertext'>Your account</a> &raquo;
		Password
	</div>
</div>
<hr class='space'/>
<?php if (in_array('DbTable', $this->types) || in_array('Array', $this->types)): ?>
<div class='span-15 colborder'>
<?php else: ?>
<div class='span-22'>
<?php endif; ?>
	<?php if (in_array('DbTable', $this->types) || in_array('Array', $this->types)): ?>
	<form id='form-edit'>
		<input type='hidden' name='base-url' value='<?php echo $this->baseUrl(); ?>'>
	</form>
	<form id='form-submit'>
		<h4>New password</h4>
		<div>
			<input type='password' name='newPassword' value=''>
		</div>

		<hr class='space'/>

		<h4>Repeat new password</h4>
		<div>
			<input type='password' name='repeatPassword' value=''>
		</div>

		<hr class='space'/>

		<div class='span-20 last clearfix form-ops' style='text-align: center;'>
			<input id='btn-save' type='button' value='Save'>
			<a class='hypertext' style='padding-left: 20px;' href='<?php echo $this->baseUrl(); ?>/settings/modify/edit?id=<?php echo $this->id; ?>'>cancel</a>
		</div>
	</form>
	<?php else: ?>
	<div class='notice'>
		The authentication types that are available do not support changing passwords.
	</div>
	<?php endif; ?>
</div>
<?php if (in_array('DbTable', $this->types) || in_array('Array', $this->types)): ?>
<div class='span-6 last' style='text-align: justify;'>
	<p>
	You can change your password using the associated form
	</p>
	<p>
	When changing the password, this will only change it in
	the database. You cannot change passwords that are used via
	LDAP or Certificates
	</p>
</div>
<?php endif; ?>
</div>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
