<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>

<div class='pagehead span-24'>
	<div class='wrapper content'>
		<h1>Using <?php echo _APPLICATION; ?></h1>
		<p>
			We're confident we can answer your question. Don't see what you're looking for? Contact us
		</p>
		<ul class='prepend-top prepend-1 append-bottom'>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=1'>What is scan-me-now?</a>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=2'>How long will the scan take?</a>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=3'>Can scan-me-now scan through my firewall?</a>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=4'>What happens if I press the Stop button or refresh the page?</a>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=5'>Can I stop the scan?</a>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=6'>Are the results saved?</a>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=7'>Can I input additional machines to scan?</a>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=8'>Can I scan my home machine connected to Fermilab through a VPN?</a>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=9'>What browsers are supported?</a>
		</ul>

		<h1>Errors</h1>
		<p>
			Hopefully you'll never actually encounter any of the topics discussed below.
		</p>
		<ul class='prepend-top prepend-1 append-bottom'>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=12'>I have waited for a long time and still have no results display. What should I do?</a>
		</ul>

		<h1>Interpreting Results</h1>
		<p>
			The results should be easy enough to interpret, but just in case, let us clarify them
		</p>
		<ul class='prepend-top prepend-1 append-bottom'>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=10'>Why does the scan only complete a portion of the total plugins available?</a>
			<li><a class='hypertext' href='<?php echo $this->baseUrl(); ?>/about/faq/answer?question=11'>What alerts should I be concerned about?</a>
		</ul>
	</div>
</div>

<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
