<?php if ($this->type == 'tag'): ?>
	<?php if (!empty($this->results)): ?>
		<?php foreach($this->results as $tag): ?>
			<?php $tagObj = new Tag($tag['permission_resource']); ?>
			<?php if ($this->inSelected($tag['permission_resource'], $this->selected)): ?>
			<li class='<?php echo $tag['permission_id']; ?>'>
				<input type='hidden' name='available-tag[]' value='<?php echo $tag['permission_id']; ?>'>
				<img src='<?php echo $this->baseUrl(); ?>/usr/images/forward-selected.png'>&nbsp;&nbsp;
				<span><?php echo $tagObj->getName(); ?></span>
			<?php else: ?>
			<li class='<?php echo $tag['permission_id']; ?>'>
				<input type='hidden' name='available-tag[]' value='<?php echo $tag['permission_id']; ?>'>
				<img src='<?php echo $this->baseUrl(); ?>/usr/images/forward.png'>&nbsp;&nbsp;
				<span><?php echo $tagObj->getName(); ?></span>
			<?php endif; ?>
		<?php endforeach; ?>
	<?php endif; ?>
<?php elseif ($this->type == 'queue'): ?>


<?php endif; ?>
