<?php require _MODPATH.'/default/views/scripts/header/index.phtml'; ?>
<?php require _MODPATH.'/admin/views/scripts/account/title.phtml'; ?>

<div class='span-23 last' style='border-color: 1px solid #fff; position: relative;'>
	<form id='form-edit'>
		<input type='hidden' name='base-url' value='<?php echo $this->baseUrl(); ?>'>
		<input type='hidden' name='page' value='1'>
	</form>

	<div id='accounts' class='block clearfix menu-content span-23'>
		<div id='content' class='content' style='padding-top: 10px;'></div>
	</div>

	<div id='pager' class='prepend-top append-bottom span-23' style='text-align: center;'></div>
</div>

	</div>
</div>
<?php require _MODPATH.'/default/views/scripts/footer/index.phtml'; ?>
